# Generated by Django 4.2.5 on 2023-10-10 07:01

import clfspeaker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clfspeaker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio_file",
            field=models.FileField(upload_to=clfspeaker.models.get_upload_to),
        ),
    ]
